### 1. Создать карточку
POST http://localhost:3000/cards
Content-Type: application/json
Authorization: Bearer 123

{
  "title": "Как работать c 5 ...",
  "text": "Изучите документацию",
  "sectionId": "685fa43012631d176ce4c5c6"
}

###

### 2. Получить все карточки
GET http://localhost:3000/cards

###

### 3. Получить карточки по секции
GET http://localhost:3000/cards/section/685fa43012631d176ce4c5c6

###

### 4. Получить карточку по ID
GET http://localhost:3000/cards/685e8bbcb4837c749bdd2a9b

###

### 5. Обновить карточку
PUT http://localhost:3001/cards/685e8bbcb4837c749bdd2a9b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzUxMDI2MzU2LCJleHAiOjE3NTEwMjk5NTZ9.XiMXBKaLUcfU2qoOPrnc5YTc45ow7ZZWJjAzje1C6-0

{
  "text": "Новое описание 2",
  "sectionId": "667d5f5b9c9d6e1d9c9d6e1d"
}

###

### 6. Удалить карточку
DELETE http://localhost:3001/cards/685e8bbcb4837c749bdd2a9b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzUxMDI2MzU2LCJleHAiOjE3NTEwMjk5NTZ9.XiMXBKaLUcfU2qoOPrnc5YTc45ow7ZZWJjAzje1C6-0
