### 1. Создать новую секцию
POST http://localhost:3000/sections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB1cGEiLCJpYXQiOjE3NTEwOTgzNjAsImV4cCI6MTc1MTEwMTk2MH0.nZT9eTlPttpphlEiaib2_7fhI_v5bRtoLq245s7bLDo

{
  "name": "Главная",
  "description": "Главная секция"
}

###

### 2. Получить все секции
GET http://localhost:3000/sections
Accept: application/json

###

### 3. Получить секцию по ID
# Замените <id> на актуальный ID из первого ответа
GET http://localhost:3000/sections/685e5cb00fa7a604c72ee322
Accept: application/json

###

### 4. Обновить секцию по ID
# Замените <id> на актуальный ID
PUT http://localhost:3000/sections/685e5cb00fa7a604c72ee322
Content-Type: application/json

{
  "name": "Главная обновлённая",
  "description": "Обновлённое описание"
}

###

### 5. Удалить секцию по ID
# Замените <id> на актуальный ID
DELETE http://localhost:3000/sections/685e5cb00fa7a604c72ee322
Accept: application/json